apiVersion: v1
data:
  default.conf: c2VydmVyIHsKCWxpc3RlbiAgICAgICA4MDsKICAgIHNlcnZlcl9uYW1lICBsb2NhbGhvc3Q7CgogICAgbG9jYXRpb24gL2Rhc2hib2FyZCB7CiAgICAgICAgcmV3cml0ZSBeL2Rhc2hib2FyZCguKikkICQxIGJyZWFrOwoJCXByb3h5X3Bhc3MgaHR0cHM6Ly9rdWJlcm5ldGVzLWRhc2hib2FyZC5rdWJlcm5ldGVzLWRhc2hib2FyZC5zdmMuY2x1c3Rlci5sb2NhbDo0NDM7CiAgICB9CiAgICAKICAgIGxvY2F0aW9uIC8gewoJCXByb3h5X3Bhc3MgaHR0cHM6Ly9hcmdvY2Qtc2VydmVyLmFyZ29jZC5zdmMuY2x1c3Rlci5sb2NhbDo0NDM7CiAgICB9Cn0=
kind: Secret
metadata:
  managedFields:
    - apiVersion: v1
      operation: Update
  name: nginx-default-conf
  namespace: nginx-router
type: Opaque
