apiVersion: v1
data:
  default.conf: c2VydmVyIHsKCWxpc3RlbiAgICAgICA4MDsKICAgIHNlcnZlcl9uYW1lICBsb2NhbGhvc3Q7CgogICAgbG9jYXRpb24gL2Rhc2hib2FyZCB7CiAgICAgICAgcmV3cml0ZSBeL2Rhc2hib2FyZCguKikkICQxIGJyZWFrOwoJCXByb3h5X3Bhc3MgaHR0cHM6Ly9teS1yZWxlYXNlLWt1YmVybmV0ZXMtZGFzaGJvYXJkOjQ0MzsKICAgIH0KICAgIAogICAgbG9jYXRpb24gLyB7CgkJcHJveHlfcGFzcyBodHRwczovL2FyZ29jZC1zZXJ2ZXIuYXJnb2NkLnN2Yy5jbHVzdGVyLmxvY2FsOjQ0MzsKICAgIH0KfQ==
kind: Secret
metadata:
  managedFields:
  - apiVersion: v1
    operation: Update
  name: nginx-default-conf
  namespace: nginx-router
type: Opaque
